# Generated by Django 3.1 on 2021-04-24 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20210401_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 9, 59, 38, 433126)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 9, 59, 38, 432711)),
        ),
        migrations.AlterField(
            model_name='elektro',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 9, 59, 38, 433456)),
        ),
        migrations.AlterField(
            model_name='elektro',
            name='el_acc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 9, 59, 38, 432278)),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 9, 59, 38, 434096)),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='tarif',
            field=models.FloatField(),
        ),
    ]
